version: '2'
services:
  webturista:
    container_name: webturista
    build:
      context: ./WebTurista/source/
      dockerfile: Dockerfile
    depends_on:
      - api
  proxyreverso:
    container_name: proxyreverso
    build:
      context: .
      dockerfile: ./Dockerfile-test
    ports:
      - "80:80"
    depends_on:
      - api
      - admin
      - webturista
  admin:
    container_name: admin
    build:
      context: ./WebAdministrador/source/
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8090:80"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - ./_volumen_compartido/db/:/data/db/
  api:
    container_name: api
    build:
      context: ./ApiSistema/source/
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    volumes:
      - ./_volumen_compartido/uploads/:/usr/src/app/public/uploads/
    depends_on:
      - mongo
  prerender:
    container_name: prerender
    build:
      context: ./Prerender/sources/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - webturista
      - proxyreverso
