version: '2'
services:
  webturista:
    container_name: webturista
    build:
      context: ./WebTurista/source/
      dockerfile: Dockerfile
    depends_on:
      - api
    volumes:
      - ./WebTurista/source/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:80"
  proxyreverso:
    container_name: proxyreverso
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - admin
      - webturista
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
  admin:
    container_name: admin
    build:
      context: ./WebAdministrador/source/
      dockerfile: Dockerfile
    depends_on:
      - api
  mongo:
    image: mongo
    restart: always
    volumes:
      - [local-data]:[docker-data]
  api:
    container_name: api
    build:
      context: ./ApiSistema/source/
      dockerfile: Dockerfile
    volumes:
      - ./uploads/:/usr/src/app/public/uploads/
    depends_on:
      - mongo
  prerender:
    container_name: prerender
    build:
      context: ./Prerender/sources/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - webturista
      - proxyreverso
